# fx-rate history of USD and JPY against KRW since 2003-12-01

In [1]:
import pandas as pd
import FinanceDataReader as fdr
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.linear_model import LinearRegression

In [2]:
pd.options.plotting.backend = 'plotly'

In [29]:
# 시작일을 2003-12-01 전으로 설정해도 2003-12-01 이후 데이터만 받을 수 있다.
df_usd = fdr.DataReader('USD/KRW', start='2003-12-01')
df_usd.head(5)

Open         High          Low        Close    Adj Close  \
Date                                                                          
2003-12-01  1197.300049  1203.500000  1195.000000  1198.400024  1198.400024   
2003-12-02  1198.099976  1198.500000  1186.199951  1195.000000  1195.000000   
2003-12-03  1195.000000  1198.400024  1192.500000  1192.500000  1192.500000   
2003-12-04  1192.599976  1197.900024  1174.800049  1190.099976  1190.099976   
2003-12-05  1189.400024  1193.800049  1178.599976  1184.699951  1184.699951   

            Volume  
Date                
2003-12-01     0.0  
2003-12-02     0.0  
2003-12-03     0.0  
2003-12-04     0.0  
2003-12-05     0.0

In [4]:
df_usd.tail(5)

Open         High          Low        Close    Adj Close  \
Date                                                                          
2022-10-25  1443.959961  1443.930054  1422.920044  1443.959961  1443.959961   
2022-10-26  1426.930054  1432.209961  1409.930054  1426.930054  1426.930054   
2022-10-27  1412.689941  1424.510010  1412.030029  1412.689941  1412.689941   
2022-10-28  1420.650024  1428.119995  1412.319946  1420.650024  1420.650024   
2022-10-29  1421.640015  1421.640015  1421.640015  1421.640015  1421.640015   

            Volume  
Date                
2022-10-25     0.0  
2022-10-26     0.0  
2022-10-27     0.0  
2022-10-28     0.0  
2022-10-29     0.0

In [5]:
df_jpy = fdr.DataReader('JPY/KRW', start='2003-12-01')
df_jpy.head(5)

Open    High     Low   Close  Adj Close  Volume
Date                                                         
2003-12-01  10.900  10.993  10.893  10.976     10.976     0.0
2003-12-02  10.974  11.015  10.885  10.989     10.989     0.0
2003-12-03  10.992  11.061  10.980  11.013     11.013     0.0
2003-12-04  11.009  11.065  10.861  10.994     10.994     0.0
2003-12-05  10.996  11.063  10.907  11.040     11.040     0.0

In [6]:
df_jpy.tail(5)

Open      High       Low     Close  Adj Close  Volume
Date                                                                 
2022-10-25  9.698071  9.708979  9.616232  9.697873   9.697873     0.0
2022-10-26  9.639069  9.667370  9.605046  9.641647   9.641647     0.0
2022-10-27  9.665499  9.759074  9.663912  9.667186   9.667186     0.0
2022-10-28  9.713540  9.719242  9.631767  9.712311   9.712311     0.0
2022-10-28  9.685000  9.702000  9.610000  9.620000   9.620000     0.0

In [7]:
df_usd.reset_index(inplace=True)
df_usd.head(5)

Date         Open         High          Low        Close    Adj Close  \
0 2003-12-01  1197.300049  1203.500000  1195.000000  1198.400024  1198.400024   
1 2003-12-02  1198.099976  1198.500000  1186.199951  1195.000000  1195.000000   
2 2003-12-03  1195.000000  1198.400024  1192.500000  1192.500000  1192.500000   
3 2003-12-04  1192.599976  1197.900024  1174.800049  1190.099976  1190.099976   
4 2003-12-05  1189.400024  1193.800049  1178.599976  1184.699951  1184.699951   

   Volume  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [8]:
df_jpy.reset_index(inplace=True)
df_jpy.head(5)


Date    Open    High     Low   Close  Adj Close  Volume
0 2003-12-01  10.900  10.993  10.893  10.976     10.976     0.0
1 2003-12-02  10.974  11.015  10.885  10.989     10.989     0.0
2 2003-12-03  10.992  11.061  10.980  11.013     11.013     0.0
3 2003-12-04  11.009  11.065  10.861  10.994     10.994     0.0
4 2003-12-05  10.996  11.063  10.907  11.040     11.040     0.0

In [9]:
df_fx = pd.merge(
    left=df_usd.loc[:, ['Date', 'Adj Close']], 
    right=df_jpy.loc[:, ['Date', 'Adj Close']], 
    how='outer', 
    on='Date',
    suffixes=('_USD', '_JPY')
)

In [10]:
df_fx

Date  Adj Close_USD  Adj Close_JPY
0    2003-12-01    1198.400024      10.976000
1    2003-12-02    1195.000000      10.989000
2    2003-12-03    1192.500000      11.013000
3    2003-12-04    1190.099976      10.994000
4    2003-12-05    1184.699951      11.040000
...         ...            ...            ...
4932 2022-10-26    1426.930054       9.641647
4933 2022-10-27    1412.689941       9.667186
4934 2022-10-28    1420.650024       9.712311
4935 2022-10-28    1420.650024       9.620000
4936 2022-10-29    1421.640015            NaN

[4937 rows x 3 columns]

In [11]:
df_fx.isna().sum()

Date              0
Adj Close_USD    31
Adj Close_JPY    32
dtype: int64

In [12]:
df_fx.fillna(method='ffill', inplace=True)
df_fx

Date  Adj Close_USD  Adj Close_JPY
0    2003-12-01    1198.400024      10.976000
1    2003-12-02    1195.000000      10.989000
2    2003-12-03    1192.500000      11.013000
3    2003-12-04    1190.099976      10.994000
4    2003-12-05    1184.699951      11.040000
...         ...            ...            ...
4932 2022-10-26    1426.930054       9.641647
4933 2022-10-27    1412.689941       9.667186
4934 2022-10-28    1420.650024       9.712311
4935 2022-10-28    1420.650024       9.620000
4936 2022-10-29    1421.640015       9.620000

[4937 rows x 3 columns]

In [13]:
px.line(
    data_frame=df_fx,
    x='Date',
    y=['Adj Close_USD', 'Adj Close_JPY'],
    title='USD, JYP 환율'
)

In [14]:
fig = make_subplots(specs=[[{'secondary_y': True}]])
fig.add_trace(go.Scatter(x=df_fx['Date'], y=df_fx['Adj Close_USD'],  name='USD'), secondary_y=False)
fig.add_trace(go.Scatter(x=df_fx['Date'], y=df_fx['Adj Close_JPY'], name='JPY'), secondary_y=True)
fig.update_layout(
    title='USD, JPY 환율',
    legend=dict(
        orientation='h',
    ),
)
fig.update_yaxes(
    title_text='KRW/USD',
    secondary_y=False
)
fig.update_yaxes(
    title_text='KRW/JPY',
    secondary_y=True
)
fig.show()


In [15]:
fig.write_html('fx_rate_USD_and_JPY_against_KRW.html')

## 분석
- 위 그래프의 스케일에서 보면 2008년까지 USD와 JPY의 환율 곡선은 거의 겹쳐있다. 
- USD와 JPY 모두 2008년 12월 ~ 2009년 3월 사이에 정점을 찍었다. 
- 그 후 2016년까지 두 곡선은 벌어져있다.
- 2016년 부터 2021년 사이에 두 곳선은 다시 겹쳐진다.
- 2021년 부터 현재까지 다시 벌어진다.

In [16]:
fig = make_subplots(specs=[[{'secondary_y': True}]])
fig.add_trace(go.Scatter(x=df_fx['Date'], y=df_fx['Adj Close_USD'],  name='USD'), secondary_y=False)
fig.add_trace(go.Scatter(x=df_fx['Date'], y=df_fx['Adj Close_JPY'], name='JPY'), secondary_y=True)
fig.update_layout(
    title='USD, JPY 환율',
    xaxis_title='year',
    legend=dict(
        orientation='h',
    ),
)
fig.update_yaxes(
    range=[700, 1700],
    title_text='KRW/USD',
    secondary_y=False
)
fig.update_yaxes(
    range=[7, 17],
    title_text='KRW/JPY',
    secondary_y=True
)
fig.show()


In [17]:
px.scatter(df_fx, x='Adj Close_USD', y='Adj Close_JPY', title='USD vs. JYP 환율')

In [18]:
df_fx['year'] = df_fx.Date.dt.year
df_fx

Date  Adj Close_USD  Adj Close_JPY  year
0    2003-12-01    1198.400024      10.976000  2003
1    2003-12-02    1195.000000      10.989000  2003
2    2003-12-03    1192.500000      11.013000  2003
3    2003-12-04    1190.099976      10.994000  2003
4    2003-12-05    1184.699951      11.040000  2003
...         ...            ...            ...   ...
4932 2022-10-26    1426.930054       9.641647  2022
4933 2022-10-27    1412.689941       9.667186  2022
4934 2022-10-28    1420.650024       9.712311  2022
4935 2022-10-28    1420.650024       9.620000  2022
4936 2022-10-29    1421.640015       9.620000  2022

[4937 rows x 4 columns]

In [19]:
px.scatter(df_fx, x='Adj Close_USD', y='Adj Close_JPY', color='year', title='USD vs. JYP 환율')

In [20]:
df_fx[['Adj Close_USD', 'Adj Close_JPY']].corr(method='pearson')

Adj Close_USD  Adj Close_JPY
Adj Close_USD       1.000000       0.584368
Adj Close_JPY       0.584368       1.000000

<img src="./correlation_coefficient.png" height="300px">

In [21]:
df_fx.values

array([[Timestamp('2003-12-01 00:00:00'), 1198.400024, 10.976, 2003],
       [Timestamp('2003-12-02 00:00:00'), 1195.0, 10.989, 2003],
       [Timestamp('2003-12-03 00:00:00'), 1192.5, 11.013, 2003],
       ...,
       [Timestamp('2022-10-28 00:00:00'), 1420.650024, 9.712311, 2022],
       [Timestamp('2022-10-28 00:00:00'), 1420.650024, 9.62, 2022],
       [Timestamp('2022-10-29 00:00:00'), 1421.640015, 9.62, 2022]],
      dtype=object)

In [22]:
# Adj Close_USD n x 1 행렬로
X = df_fx.values[:, 1:2]
X


array([[1198.400024],
       [1195.0],
       [1192.5],
       ...,
       [1420.650024],
       [1420.650024],
       [1421.640015]], dtype=object)

In [23]:
# Adj Close_JPY 1 x n 행렬로
Y = df_fx.values[:, 2]
Y

array([10.976, 10.989, 11.013, ..., 9.712311, 9.62, 9.62], dtype=object)

In [24]:
fit = LinearRegression().fit(X, Y)

m = fit.coef_.flatten()
b = fit.intercept_.flatten()
print(f'{m = }')
print(f'{b = }')

m = array([0.01062033])
b = array([-1.07636166])


In [25]:
X_ = np.arange(df_fx['Adj Close_USD'].min(), df_fx['Adj Close_USD'].max() + 100, 100)
X_


array([ 886.679993,  986.679993, 1086.679993, 1186.679993, 1286.679993,
       1386.679993, 1486.679993, 1586.679993])

In [26]:
Y_ = m * X_ + b
Y_

array([ 8.34047038,  9.40250315, 10.46453592, 11.52656868, 12.58860145,
       13.65063421, 14.71266698, 15.77469974])

In [27]:
fig1 = go.Figure()
fig1.add_trace(
    go.Scatter(
        x=df_fx['Adj Close_USD'], 
        y=df_fx['Adj Close_JPY'], 
        name='data', 
        mode='markers', 
        marker=dict(
            color=df_fx['year'],
            showscale=True,
            colorbar=dict(
                thickness=5,
                # tickvals=[-5, 5],
                # ticktext=['low', 'high'],
                outlinewidth=0,
            )
        ),
        text=df_fx['year'],
    )
)
fig1.add_trace(
    go.Scatter(
        x=X_, 
        y=Y_, 
        name='regression', 
        mode='lines+markers', 
        marker_color='red',
    )
)
fig1.update_layout(
    title='USD vs JPY 환율',
    xaxis_title='KRW/USD',
    yaxis_title='KRW/JPY',
    legend=dict(
        orientation='h',
    ),
)
fig1.show()


In [28]:
fig1.write_html('fx_rate_USD_vs_JPY.html')

## 참조
- 아래 그래프들은 2003년 이전의 환율을 참조하기 위해서 www.ceicdata.com에서 다운로드 받은 것들이다.

### KRW/USD fx-rate

<img src='USD_KRW_fx_rate.svg' width='800px' height='600px'>

### KRW/USD fx-rate

<img src='USD_JPY_fx_rate.svg' width='800px' height='600px'>